"""Initial schema

Revision ID: 1550d266492c
Revises: 
Create Date: 2026-03-27 21:08:06.441157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1550d266492c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name')
    )
    op.create_table('detected_objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('object_name', sa.String(length=200), nullable=False),
    sa.Column('object_category', sa.String(length=100), nullable=False),
    sa.Column('object_material', sa.String(length=200), nullable=True),
    sa.Column('object_brand', sa.String(length=100), nullable=True),
    sa.Column('object_condition', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reuse_suggestions', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_hash')
    )
    op.create_index(op.f('ix_detected_objects_ai_provider'), 'detected_objects', ['ai_provider'], unique=False)
    op.create_index(op.f('ix_detected_objects_created_at'), 'detected_objects', ['created_at'], unique=False)
    op.create_index(op.f('ix_detected_objects_object_category'), 'detected_objects', ['object_category'], unique=False)
    op.create_table('energy_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('energy_score', sa.Integer(), nullable=True),
    sa.Column('kwh_per_unit', sa.Float(), nullable=True),
    sa.Column('kwh_per_kg', sa.Float(), nullable=True),
    sa.Column('valorization_methods', sa.Text(), nullable=False),
    sa.Column('waste_hierarchy_level', sa.String(length=50), nullable=True),
    sa.Column('ler_code', sa.String(length=20), nullable=True),
    sa.Column('is_hazardous', sa.Boolean(), nullable=True),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['detected_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy_data')
    op.drop_index(op.f('ix_detected_objects_object_category'), table_name='detected_objects')
    op.drop_index(op.f('ix_detected_objects_created_at'), table_name='detected_objects')
    op.drop_index(op.f('ix_detected_objects_ai_provider'), table_name='detected_objects')
    op.drop_table('detected_objects')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
